pokus 1

diff --git a/.github/workflows/angular-test_greyhill-test.yml b/.github/workflows/angular-test_greyhill-test.yml
--- a/.github/workflows/angular-test_greyhill-test.yml
+++ b/.github/workflows/angular-test_greyhill-test.yml
@@ -1,7 +1,7 @@
 # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
 # More GitHub Actions for Azure: https://github.com/Azure/actions
 
-name: Build and deploy Node.js app to Azure Web App - greyhill-test
+name: UI Test - greyhill-test
 
 on:
   push:
@@ -10,10 +10,10 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  build-angular:
     runs-on: ubuntu-latest
     permissions:
-      contents: read #This is required for actions/checkout
+      contents: read
 
     steps:
       - uses: actions/checkout@v4
@@ -23,31 +23,47 @@ jobs:
         with:
           node-version: '20.x'
 
-      - name: npm install, build, and test
+      - name: npm install
+        working-directory: client
+        run: npm install
+
+      - name: ng build production
+        working-directory: client
+        run: npx ng build --configuration production #nefungovalo na github actions
+        #run: ng build --configuration production
+
+      - name: Create ZIP artifact
+        working-directory: client
         run: |
-          npm install
-          npm run build --if-present
-          npm run test --if-present
+          if [ -d "dist" ]; then
+            cd dist && zip -r ../release.zip . && cd ..
+          else
+            echo "ERROR: dist directory not found. Build may have failed."
+            exit 1
+          fi
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
-          name: node-app
-          path: .
+          name: angular-app
+          path: client/release.zip
 
-  deploy:
+  deploy-angular:
     runs-on: ubuntu-latest
-    needs: build
+    needs: build-angular
     permissions:
-      id-token: write #This is required for requesting the JWT
-      contents: read #This is required for actions/checkout
+      id-token: write
+      contents: read
 
     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
         with:
-          name: node-app
-      
+          name: angular-app
+
+      - name: Unzip artifact
+        run: unzip release.zip
+
       - name: Login to Azure
         uses: azure/login@v2
         with:
@@ -61,5 +77,5 @@ jobs:
         with:
           app-name: 'greyhill-test'
           slot-name: 'Production'
-          package: .
+          package: ./
           
